version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: school_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432" # host:container -> maps host 5433 to Postgres 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
